version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 2345
      POSTGRES_USER: app
      POSTGRES_DB: db

  adminer:
    image: adminer
    restart: always
    ports:
      - 9999:3306